# Site
repository: surya-kanoria/surya-kanoria.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Surya Kanoria
# title: Machine Learning Engineer
email: suryakanoria@gmail.com
description: Professional website for Surya Kanoria
# website: https://surya-kanoria.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: suryakanoria
github_username:  surya-kanoria
author: Surya Kanoria

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: suryakanoria
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Surya.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Surya and I am a Machine Learning Engineer at Spotify working on Reinforcement Learning for music recommendations at a scale of millions of users. I am excited about applying state-of-the-art machine learning / reinforcement learning in the industry. Before Spotify, I worked in the [Chicago Human + AI Lab](https://chicagohai.github.io/). My research interest includes:
  - Recommender systems 
  - Better Human-AI interaction by developing a better understanding of machine learning models.
  - Scaling machine learning models and practices for hundreds of millions of users in the industry.

  I have four years of software engineering experience at Flipkart where I developed machine learning, backend and front-end systems for ~100 million users. 

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: top-left
      title: University of Colorado Boulder
      caption: 2019 - 2020
      sub_title: MS in Computer Science
      # link_text: Project Website
      # quote: >
      #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
      description: I completed my Master's with a focus on Data Science and Engineering. My research projects were advised by Prof. Chenhao Tan in which I worked on the interpretability of transformer networks and Dr. Geena Kim where I used bird images to generate bird sounds using GANs. 
      
    - layout: top-left
      title: Birla Institute of Technology and Science, Pilani
      caption: 2011 - 2015
      sub_title: Bachelor of Engineering (Hons), Chemical Engineering
      description: During my time at BITS Pilani, I found my interests evolving towards programming and took several computer science courses to develop a strong foundation in computer science. 
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Spotify
        sub_title: Machine Learning Engineer
        caption: May 2021 - Present
        description: Currently working on Reinforcement Learning for music recommendations for millions of Spotify users.
      
      - layout: left
        title: Spotify
        sub_title: Machine Learning Intern
        caption: May 2020 - December 2020
        description: Developed end to end machine learning pipeline at Spotify that allows music personalization for new users. Implemented data aggregation, feature engineering, a learning to rank mode and real-time predictions for 300 million users.

      - layout: left
        title: Flipkart
        sub_title: Senior Software Engineer, Machine Learning
        caption: April 2018 - August 2019
        description: I worked with user generated content like product reviews and questions, where I primarily worked on developing a personalized review recommendation system for users. In addition, I also worked on developing a question-answering system and a context-based spell correction system for non-native english speakers.
      
      - layout: left
        title: Flipkart
        sub_title: Senior Software Engineer
        caption: August 2017 - March 2018
        description: I co-founded a new team to develop a cross-platform framework which allows same code to run with no performance hits on all mobile platforms - android, iOS and mobile-web. I also played a key role in development of a new developer platform which allowed other companies in India to run their applications inside the Flipkart mobile app and integrate with the Flipkart eco-system.

      - layout: left
        title: Flipkart
        sub_title: Software Engineer
        caption: July 2015 - July 2017
        description: I led new initiatives for windows, mobile-web and android platforms. My most notable contribution was to single-handedly develop an open-source library called [DUS](https://github.com/Flipkart/DUS) for updating source code on android applications on the fly. 

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top
        title: What to Learn, and How Toward Effective Learning from Rationales
        caption: Jan 2021 - May 2021
        sub_title: Chicago Human + AI Lab
        description: https://arxiv.org/abs/2112.00071
      
      - layout: top
        title: Interpretability of Transformer Network
        caption: Aug 2020 - Dec 2019
        sub_title: University of Colorado Boulder
        description: Worked on my master's research project advised by Dr. Chenhao Tan. We examined the amount of information preseved about input words in the hidden representations of BERT. Submitted a research paper to ACL based on our results.
      
      - layout: top
        title: Sound generation based on visual input
        caption: Jan 2020 - May 2019
        sub_title: University of Colorado Boulder
        description: Worked on my master's research project under Dr. Geena Kim to develop a neural network which learns multi-modal association between bird images and bird sounds. Developed a custom Generative Adverserial Network by adapting Tacotron, VGG19 & speech synthesis models.
      
      - layout: top
        title: Voice Command Recognition
        caption: September 2019 - December 2019
        sub_title: University of Colorado Boulder
        description: Developed a speech recognition system on Tensorflow which could translate short voice commands to text. Used speech processing feature extraction algorithms like MFCC and implemented dynamic CNNs networks to translate the extracted spectrograms to short texts.
      
      - layout: top
        title: Interpretable Machine Learning for Diabetes Patient Readmission
        caption: September 2019 - December 2019
        sub_title: University of Colorado Boulder
        description: Developed a machine learning model that uses medical records to predict if a patient is going to get re-admitted to the hospital. The model is interpretable and could identify the factors that leads to readmission.

      - layout: top
        title: Personalised Review Ranking
        caption: August 2018 - July 2019
        sub_title: Flipkart/IIT Kharagpur
        description: | # this will include new lines to allow paragraphs
          Implemented Aspect Extraction of Reviews and Collaborative Filtering using Deep Neural Networks to learn joint embeddings of review features, user profile, the temporal context in TensorFlow. Released as a live A/B experiment for 100 million users on Flipkart

      - layout: top
        title: Question Answering System
        caption: May 2018 - May 2019
        sub_title: Flipkart/IIT Kharagpur
        description: Mentored a Masters student to develop an auto-answering of questions asked by users using product specifications and user reviews. Used key-value memory networks and dual space embedding models in TensorFlow to select the right specification/review to answer a query.

      - layout: top
        title: Context-based spell correction system
        caption: June 2018 - Aug 2019
        sub_title: Flipkart/IIT Kharagpur
        description: Developed a spell correction system to aid non-native English speakers for product reviews written on Flipkart. Implemented Recurrent Neural Networks with Gated Recurrent Unit nodes trained on a labelled set of corrected sentences in TensorFlow.

      - layout: top
        title: Dynamic Update System
        caption: June 2016 - Sep 2016
        sub_title: Flipkart
        description: Conceptualized, designed and developed a differential-sync system for delivering instant updates for React Native bundles for the Flipkart Mobile Apps. Modified the obfuscation logic of React Native Packager enabling both selective downloading of only the changes in bundles, as well as sharing of code across multiple bundles, previously not possible. Made several other optimizations eventually reducing the download size by ~95%.

  - title: Teaching # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top
        title: Teaching Assistant
        caption: August 2020 - December 2020
        sub_title: University of Colorado Boulder
        description: | 
          - Conducted weekly recitations for final year computer science students where I teach standard software engineering tools and processes.
          - Conducted weekly stand-ups with student project groups to help them manage their course projects.

      - layout: top
        title: Graduate Student Staff
        caption: August 2019 - May 2020
        sub_title: University of Colorado Boulder
        description: | 
          - Conducted office-hours and was reponsible for grading homework and exams for CSCI 2824 - Discrete Structures
        

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
